name: Coolify Helper Image

on:
  workflow_call:
    inputs:
      ref:
        description: Git ref to build.
        required: false
        type: string
        default: v4.x
    outputs:
      version:
        description: Coolify helper image version.
        value: ${{ jobs.resolve.outputs.version }}

permissions:
  contents: read
  packages: write

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: "loccen/coolify-helper"
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_PROD_RELEASE_CHANNEL }}

jobs:
  resolve:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: Get Version
        id: version
        run: |
          echo "version=$(docker run --rm -v "$(pwd):/app" -w /app php:8.2-alpine3.16 php bootstrap/getHelperVersion.php)" >> "$GITHUB_OUTPUT"

  build-push:
    needs: resolve
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-24.04
          - arch: aarch64
            platform: linux/aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: Login to ${{ env.GITHUB_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Build and Push Image (${{ matrix.arch }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/coolify-helper/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.resolve.outputs.version }}-${{ matrix.arch }}
          labels: |
            coolify.managed=true
  merge-manifest:
    runs-on: ubuntu-24.04
    needs:
      - resolve
      - build-push
    steps:
      - uses: docker/setup-buildx-action@v3

      - name: Login to ${{ env.GITHUB_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Create & publish manifest on ${{ env.GITHUB_REGISTRY }}
        run: |
          docker buildx imagetools create \
          ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.resolve.outputs.version }}-amd64 \
          ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.resolve.outputs.version }}-aarch64 \
          --tag ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.resolve.outputs.version }} \
          --tag ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - uses: sarisia/actions-status-discord@v1
        if: ${{ always() && env.DISCORD_WEBHOOK != '' }}
        with:
          webhook: ${{ env.DISCORD_WEBHOOK }}
