name: Generate Changelog

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 目标分支
        required: false
        type: string
        default: v4.x

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ inputs.target_branch }}
          branch: automation/update-changelog
          delete-branch: true
          commit-message: "docs: 更新更新日志"
          title: "docs: 更新更新日志"
          body: |
            该 PR 由 `Generate Changelog` workflow 自动生成。
          add-paths: |
            CHANGELOG.md
